#!/usr/bin/env python
# -*- coding: utf-8 -*-

from random import randint

vitamina_a=['noz', 'cacao', 'avela', 'amendoa', 'sardinha', 'peixe', 'caranguejo', 'camarao', 'badejo', 'bacalhau', 'atum', 'pizza', 'pao_doce', 'panqueca', 'panetone', 'lasanha', 'hamburguer', 'esfirra', 'coxinha', 'bolo', 'lentilha', 'feijao', 'ervilha', 'amendoim', 'requeijao', 'queijo', 'margarina', 'manteiga', 'leite', 'iorgute', 'vagem', 'tomate', 'pimentao', 'mostarda', 'manjericao', 'jilo', 'inhame', 'fava', 'espinafre', 'couve', 'coentro', 'cenoura', 'cebolinha', 'catalonha', 'caruru', 'cara', 'beterraba', 'batata_doce', 'batata', 'almeirao', 'alho', 'agriao', 'acelga', 'abobrinha', 'abobora', 'uva', 'tangerina', 'tamarindo', 'pitomba', 'pitanga', 'pessego', 'pera', 'pequi', 'nespera', 'morango', 'melao', 'melancia', 'maracuja', 'manga', 'mamao', 'maca', 'limao', 'laranja', 'kiwi', 'jambo', 'jaca', 'goiaba', 'figo', 'cereja', 'carambola', 'banana', 'acerola', 'abacaxi', 'abacate', 'pao_integral', 'milho', 'porco', 'peru', 'ovo', 'frango', 'figado', 'cha', 'leite_cafe', 'leite', 'cocada', 'doce_leite', 'achocolatado']
vitamina_b=['pupunha', 'noz', 'castanha', 'coco', 'cacao', 'avela', 'amendoa', 'sardinha', 'peixe', 'manjuba', 'caranguejo', 'camarao', 'bacalhau', 'atum', 'torrada', 'tapioca', 'pizza', 'pao_doce', 'panqueca', 'panetone', 'macarrao', 'lasanha', 'hamburguer', 'esfirra', 'crepioca', 'coxinha', 'bolo', 'soja', 'lentilha', 'feijao', 'ervilha', 'amendoim', 'requeijao', 'queijo', 'margarina', 'manteiga', 'leite', 'iorgute', 'vagem', 'tomate', 'rabanete', 'pimentao', 'pepino', 'palmito', 'nabo', 'mostarda', 'maxixe', 'manjericao', 'jilo', 'inhame', 'fava', 'espinafre', 'couve_flor', 'couve', 'coentro', 'chuchu', 'cenoura', 'cebolinha', 'cebola', 'catalonha', 'caruru', 'cara', 'beterraba', 'batata_doce', 'batata', 'almeirao', 'alho', 'aipo', 'agriao', 'acelga', 'abobrinha', 'bobora', 'uva', 'tangerina', 'tamarindo', 'seriguela', 'roma', 'pinha', 'pessego', 'pera', 'nespera', 'morango', 'melao', 'melancia', 'maracuja', 'manga', 'mamao', 'maca', 'limao', 'laranja', 'kiwi', 'jaca', 'jabuticaba', 'goiaba', 'figo', 'cupuacu', 'cereja', 'carambola', 'caqui', 'caju', 'banana', 'ata', 'acai', 'abacaxi', 'abacate', 'polenta', 'pao_integral', 'milho', 'canjica', 'baiao', 'aveia', 'arroz_integral', 'arroz', 'porco', 'peru', 'ovo', 'linguiça', 'frango', 'figado', 'boi','cha', 'cerveja', 'cana', 'leite', 'cafe','achocolatado', 'chocolate', 'cocada', 'doce_leite', 'mel']
vitamina_c=['pupunha', 'noz', 'coco', 'avela', 'caranguejo', 'tapioca', 'pizza', 'lasanha', 'hamburguer', 'coxinha', 'lentilha', 'ervilha', 'iorgute', 'vagem', 'tomate', 'rabanete', 'pimentao', 'pepino', 'palmito', 'nabo', 'mostarda', 'maxixe', 'manjericao', 'mandioca', 'jilo', 'inhame', 'fava', 'espinafre', 'couve_flor', 'couve', 'coentro', 'chuchu', 'cenoura', 'cebolinha', 'cebola', 'catalonha', 'caruru', 'cara', 'beterraba', 'batata_doce', 'batata', 'almeirao', 'alho', 'aipo', 'agriao', 'acelga', 'abobrinha', 'abobora', 'uva', 'umbu', 'tangerina', 'tamarindo', 'seriguela', 'roma', 'pitomba', 'pitanga', 'pinha', 'pessego', 'pera', 'pequi', 'morango', 'melao', 'melancia', 'maracuja', 'manga', 'mamao', 'macauba', 'maca', 'limao', 'laranja', 'iwi', 'jambo', 'jaca', 'jabuticaba', 'graviola', 'goiaba', 'figo', 'cupuacu', 'cereja', 'carambola', 'caqui', 'caja', 'banana', 'ata', 'acerola', 'acai', 'abiu', 'abacaxi', 'abacate', 'leite_cafe', 'leite', 'agua_coco', 'cocada', 'doce_leite', 'geleia', 'mel']
vitamina_d=['peixe', 'manjuba', 'camarao', 'badejo', 'bacalhau', 'atum', 'queijo', 'porco', 'peru', 'ovo', 'frango', 'figado', 'boi', 'bacon', 'achocolatado', 'doce_leite']
vitamina_e=['noz', 'castanha', 'cacao', 'avela', 'amendoa', 'sardinha', 'manjuba', 'camarao', 'badejo', 'oleo', 'azeite', 'panqueca', 'coxinha', 'amendoim', 'queijo', 'margarina', 'manteiga', 'mostarda', 'espinafre', 'coentro', 'cenoura', 'catalonha', 'agriao', 'acelga', 'pequi', 'melancia', 'macauba', 'kiwi', 'jabuticaba', 'abacate', 'pao_integral', 'ovo', 'bacon', 'achocolatado', 'chocolate', 'doce_leite', 'geleia']
#vitamina_h=['canela', 'lombo', 'perna', 'lingua']
vitamina_k=['noz', 'cacao', 'sardinha', 'oleo', 'azeite', 'ervilha', 'manteiga', 'manjericao', 'batata_doce', 'batata', 'alho', 'aipo', 'agriao', 'acelga', 'abobrinha', 'abobora', 'tamarindo', 'roma', 'pessego', 'pera', 'morango', 'melao', 'manga', 'maca', 'kiwi', 'goiaba', 'figo', 'cereja', 'abacaxi', 'abacate', 'pao_integral', 'figado', 'achocolatado', 'chocolate', 'doce_leite']


vitamina_a2=['Gergelim', 'Lagosta', 'Vatapá', 'Salpicão', 'Feijoada', 'Cream Cracker', 'Quiabo', 'Alface', 'Berinjela', 'Chicória', 'Brócolis', 'Ameixa', 'Biscoito', 'Pato no tucupi', 'Noz', 'Cação', 'Avelã', 'Amêndoa', 'Sardinha', 'Peixe', 'Caranguejo', 'Camarão', 'Badejo', 'Bacalhau', 'Atum', 'Pizza', 'Pão Doce', 'Panqueca', 'Panetone', 'Lasanha', 'Hambúrguer', 'Esfirra', 'Coxinha', 'Bolo', 'Lentilha', 'Feijão', 'Ervilha', 'Amendoim', 'Requeijão', 'Queijo', 'Margarina', 'Manteiga', 'Leite', 'Iogurte', 'Vagem', 'Tomate', 'Pimentão', 'Mostarda', 'Manjericão', 'Jiló', 'Inhame', 'Fava', 'Espinafre', 'Couve', 'Coentro', 'Cenoura', 'Cebolinha', 'Catalonha', 'Caruru', 'Cará', 'Beterraba', 'Batata inglesa_doce', 'Batata inglesa', 'Almeirão', 'Alho', 'Agrião', 'Acelga', 'Abobrinha', 'Abóbora', 'Uva', 'tangerina', 'Tamarindo', 'Pitomba', 'Pitanga', 'Pêssego', 'Pera', 'Pequi', 'Nêspera', 'Morango', 'Melão', 'Melancia', 'Maracujá', 'Manga', 'Mamão', 'Maçã', 'Limão', 'Laranja', 'Kiwi', 'Jambo', 'Jaca', 'Goiaba', 'Figo', 'Cereja', 'Carambola', 'Banana', 'Acerola', 'Abacaxi', 'Abacate', 'Pão integral', 'Milho', 'Porco', 'Peru', 'Ovo', 'Frango', 'Fígado', 'Chá', 'Leite com café', 'Leite', 'Cocada', 'Doce de Leite', 'Achocolatado']
vitamina_b2=['Gergelim', 'Lagosta', 'Vatapá', 'Salpicão', 'Enroladinho', 'Cream Cracker', 'Quiabo', 'Alface', 'Berinjela', 'Chicória', 'Brócolis', 'Ameixa', 'Cuscuz', 'Biscoito', 'Pato no tucupi', 'pupunha', 'Noz', 'Castanha', 'Coco', 'Cação', 'Avelã', 'Amêndoa', 'Sardinha', 'Peixe', 'Manjuba', 'Caranguejo', 'Camarão', 'Bacalhau', 'Atum', 'Torrada', 'Tapioca', 'Pizza', 'Pão Doce', 'Panqueca', 'Panetone', 'Macarrão', 'Lasanha', 'Hambúrguer', 'Esfirra', 'Crepioca', 'Coxinha', 'Bolo', 'Soja', 'Lentilha', 'Feijão', 'Ervilha', 'Amendoim', 'Requeijão', 'Queijo', 'Margarina', 'Manteiga', 'Leite', 'Iogurte', 'Vagem', 'Tomate', 'rabanete', 'Pimentão', 'Pepino', 'Palmito', 'Nabo', 'Mostarda', 'Maxixe', 'Manjericão', 'Jiló', 'Inhame', 'Fava', 'Espinafre', 'Couve-Flor', 'Couve', 'Coentro', 'Chuchu', 'Cenoura', 'Cebolinha', 'Cebola', 'Catalonha', 'Caruru', 'Cará', 'Beterraba', 'Batata inglesa_doce', 'Batata inglesa', 'Almeirão', 'Alho', 'Aipo', 'Agrião', 'Acelga', 'Abobrinha', 'Abóbora', 'Uva', 'Tangerina', 'Tamarindo', 'Seriguela', 'Romã', 'Pinha', 'Pêssego', 'Pera', 'Nêspera', 'Morango', 'Melão', 'Melancia', 'Maracujá', 'Manga', 'Mamão', 'Maçã', 'Limão', 'Laranja', 'Kiwi', 'Jaca', 'Jabuticaba', 'Goiaba', 'Figo', 'Cupuaçu', 'Cereja', 'Carambola', 'Caqui', 'Caju', 'Banana', 'Ata', 'Açai', 'Abacaxi', 'Abacate', 'Polenta', 'Pão integral', 'Milho', 'Canjica', 'Baião', 'Aveia', 'Arroz integral', 'Arroz', 'Porco', 'Peru', 'Ovo', 'Linguiça', 'Frango', 'Fígado', 'Boi','Chá', 'Cerveja', 'Cana', 'Leite', 'Café','Achocolatado', 'Chocolate', 'Cocada', 'Doce de Leite', 'Mel']
vitamina_c2=['Gergelim', 'Lagosta', 'Vatapá', 'Salpicão', 'Feijoada', 'Quiabo', 'Alface', 'Berinjela', 'Brócolis', 'pupunha', 'Noz', 'Coco', 'Avelã', 'Caranguejo', 'Tapioca', 'Pizza', 'Lasanha', 'Hambúrguer', 'Coxinha', 'Lentilha', 'Ervilha', 'Iogurte', 'Vagem', 'Tomate', 'rabanete', 'Pimentão', 'Pepino', 'Palmito', 'Nabo', 'Mostarda', 'Maxixe', 'Manjericão', 'Mandioca', 'Jiló', 'Inhame', 'Fava', 'Espinafre', 'Couve-Flor', 'Couve', 'Coentro', 'Chuchu', 'Cenoura', 'Cebolinha', 'Cebola', 'Catalonha', 'Caruru', 'Cará', 'Beterraba', 'Batata inglesa_doce', 'Batata inglesa', 'Almeirão', 'Alho', 'Aipo', 'Agrião', 'Acelga', 'Abobrinha', 'Abóbora', 'Uva', 'Umbu', 'tangerina', 'Tamarindo', 'Seriguela', 'Romã', 'Pitomba', 'Pitanga', 'Pinha', 'Pêssego', 'Pera', 'Pequi', 'Morango', 'Melão', 'Melancia', 'Maracujá', 'Manga', 'Mamão', 'Macaúba', 'Maçã', 'Limão', 'Laranja', 'Kiwi', 'Jambo', 'Jaca', 'Jabuticaba', 'Graviola', 'Goiaba', 'Figo', 'Cupuaçu', 'Cereja', 'Carambola', 'Caqui', 'Cajá', 'Banana', 'Ata', 'Acerola', 'Açai', 'Abiu', 'Abacaxi', 'Abacate', 'Leite com café', 'Leite', 'Água de Coco', 'Cocada', 'Doce de Leite', 'Geleia', 'Mel']
vitamina_d2=['Vatapá', 'Enroladinho', 'Peixe', 'Manjuba', 'Camarão', 'Badejo', 'Bacalhau', 'Atum', 'Queijo', 'Porco', 'Peru', 'Ovo', 'Frango', 'Fígado', 'Boi', 'Bacon', 'Achocolatado', 'Doce de Leite']
vitamina_e2=['Vatapá', 'Salpicão', 'Chicória', 'Biscoito', 'Noz', 'Castanha', 'Cação', 'Avelã', 'Amêndoa', 'Sardinha', 'Manjuba', 'Camarão', 'Badejo', 'Óleo', 'Azeite', 'Panqueca', 'Coxinha', 'Amendoim', 'Queijo', 'Margarina', 'Manteiga', 'Mostarda', 'Espinafre', 'Coentro', 'Cenoura', 'Catalonha', 'Agrião', 'Acelga', 'Pequi', 'Melancia', 'Macaúba', 'Kiwi', 'Jabuticaba', 'Abacate', 'Pão integral', 'Ovo', 'Bacon', 'Achocolatado', 'Chocolate', 'Doce de Leite', 'Geleia']
vitamina_k2=['Enroladinho', 'Quiabo', 'Alface', 'Berinjela', 'Chicória', 'Brócolis', 'Biscoito', 'Noz', 'Cação', 'Sardinha', 'Óleo', 'Azeite', 'Ervilha', 'Manteiga', 'Manjericão', 'Batata inglesa_doce', 'Batata inglesa', 'Alho', 'Aipo', 'Agrião', 'Acelga', 'Abobrinha', 'Abóbora', 'Tamarindo', 'Romã', 'Pêssego', 'Pera', 'Morango', 'Melão', 'Manga', 'Maçã', 'Kiwi', 'Goiaba', 'Figo', 'Cereja', 'Abacaxi', 'Abacate', 'Pão integral', 'Fígado', 'Achocolatado', 'Chocolate', 'Doce de Leite']



vitaminas=[vitamina_a, vitamina_b, vitamina_c, vitamina_d, vitamina_e, vitamina_k]

sem_vitaminas=['Pamonha', 'Farofa', 'Cafe com Leite', 'Refrigerante']

# Pegar tamanho das listas de vitaminas
len_a=len(vitamina_a)
len_b=len(vitamina_b)
len_c=len(vitamina_c)
len_d=len(vitamina_d)
len_e=len(vitamina_e)
len_k=len(vitamina_k)
#len_h=len(vitamina_h)

# Sortear um alimento de cada vitamina
random_a=vitamina_a[randint(0,len_a-1)]
random_b=vitamina_b[randint(0,len_b-1)]
random_c=vitamina_c[randint(0,len_c-1)]
random_d=vitamina_d[randint(0,len_d-1)]
random_e=vitamina_e[randint(0,len_e-1)]
random_k=vitamina_k[randint(0,len_k-1)]
#random_h=vitamina_h[randint(0,len_h-1)]
